Numpy 

In [62]:
# Creating NumPu ndarrays and performing basic operations

import numpy as np
# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
# Print the array and its type
print(array_1d)
print(array_1d.dtype)
# print the shape of the array
print(x.dtype)
print("array lenght", array_1d.shape)

[1 2 3 4 5]
int64
int64
array lenght (5,)


In [63]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)
print("2D array shape:", array_2d.shape)
print("2D array dtype:", array_2d.dtype)


[[1 2 3]
 [4 5 6]]
2D array shape: (2, 3)
2D array dtype: int64


In [64]:
# You can assign a specific data type while creating the array
array_float = np.array([1, 2, 3, 4, 5], dtype=np.float64)
print(array_float)
print("Float array dtype:", array_float.dtype)


[1. 2. 3. 4. 5.]
Float array dtype: float64


In [65]:
## Save the NumPy array to a File
array = np.array([1, 2, 3, 4, 5])

## We save x into the current directory as
np.save('my_array', array)
array_from_file = np.load('my_array.npy')
print(array_from_file)

[1 2 3 4 5]


In [66]:
# Using Built-in Functions to Create ndarrays
# creates an ndarray full of zeros with the given shape
zero_array = np.zeros((3, 4))
print("Zero Array:\n", zero_array)
array_of_ones = np.ones((2, 3))
print("Array of Ones:\n", array_of_ones)
print("\n")
print("Size of the array:", zero_array.size)
print("Shape of the array:", zero_array.shape)

## the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.
print("Item size of the array:", zero_array.itemsize)

Zero Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]


Size of the array: 12
Shape of the array: (3, 4)
Item size of the array: 8


In [67]:
# Using a NumPy function, how would you create a one-dimensional NumPy array of the numbers from 10 to 100, counting by 10
print(np.arange(10, 110, 10))



[ 10  20  30  40  50  60  70  80  90 100]


In [68]:
# create identity matrix
identity_matrix = np.eye(4)
print("Identity Matrix:\n", identity_matrix)
print("----------------------")
diag_matrix = np.diag([1, 2, 3, 4])
print("Diagonal Matrix:\n", diag_matrix)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
----------------------
Diagonal Matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [69]:
print(np.arange(1,3)) # numbers from 1 to 2
print(np.arange(1,20,2)) # odd numbers from 1 to 20
print(np.linspace(0,1,5))  # 5 values between 0 and 1 inclusive
print(np.linspace(0,1,5,endpoint=False))  # 5 values between 0 and 1 exclusive of 1

[1 2]
[ 1  3  5  7  9 11 13 15 17 19]
[0.   0.25 0.5  0.75 1.  ]
[0.  0.2 0.4 0.6 0.8]


In [72]:
array = np.arange(20)
print("Array:", array)
print("Change dimensions of the array:",np.reshape(array,(4,5)))

#or combine in one step
np.arange(20).reshape(4,5)


Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Change dimensions of the array: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Exercise:
Using the NumPy functions you learned about on the previous page, create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive).

In [75]:
import numpy as np

# Replace None with appropriate code
X = np.arange(2, 34, 2).reshape(4, 4)

### Notebook grading
solution = np.arange(2,34,2).reshape(4,4)

if type(X) != np.ndarray:
    print("`X` should be an ndarray")
elif np.array_equal(X, solution):
    print("Nice work! You can view my solution below")
elif X.shape != solution.shape:
    print("Your answer for `X` has a shape of {} but it should be 4 x 4".format(X.shape))
else:
    print("Your answer for `X` has the right shape but incorrect values")

Nice work! You can view my solution below


# Accessing, Deleting, and Inserting Elements Into ndarrays

In [77]:
array = np.array([1,2,3,4,5,6])
print("First Element", array[0])
print("Last Element", array[-1])
print("Slice array", array[1:4])  # elements from index 1 to 3

First Element 1
Last Element 6
Slice array [2 3 4]


# References:
- https://codesolid.com/numpy-practice-questions-to-make-you-an-expert/

# Slicing ndarrays

In [ ]:
array = np.arange(1, 13)
print(array[1:10:2])  # elements from index 1 to 9 with a step of 2


array_1 = np.arange(1, 21).reshape(4, 5)
print("Array:", array_1)

print("Get element at row 2, column 3:")  # element at row index 2
print(array_1[1:4, 2:5])
print(array_1[1:, 2:]) # rows from index 1 to end and columns from index 2 to end


[ 2  4  6  8 10]
Array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Get element at row 2, column 3
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [85]:
# copy array
original_array = np.array([1, 2, 3, 4, 5])
copied_array = original_array.copy()

# slicing array
sliced_array = original_array[1:4]
print("Original Array:", original_array)
print("Copied Array:", copied_array)
print("Sliced Array:", sliced_array)

Original Array: [1 2 3 4 5]
Copied Array: [1 2 3 4 5]
Sliced Array: [2 3 4]


In [87]:
# Boolean Indexing, Set Operations, and Sorting
array = np.array([10, 15, 20, 25, 30, 35, 40])
# Boolean indexing to filter elements greater than 25
filtered_array = array[array > 25]
print("Filtered Array (elements > 25):", filtered_array)

#assign values based on condition -1 <=15
array[array <= 15] = -1
print("Array after assignment:", array)


Filtered Array (elements > 25): [30 35 40]
Array after assignment: [-1 -1 20 25 30 35 40]


In [89]:
# interescrt and union
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])
intersection = np.intersect1d(array1, array2)
print("Intersection:", intersection)
union = np.union1d(array1, array2)
print("Union:", union)
set_diff = np.setdiff1d(array1, array2)
print("Set Difference (array1 - array2):", set_diff)

Intersection: [4 5]
Union: [1 2 3 4 5 6 7 8]
Set Difference (array1 - array2): [1 2 3]


In [93]:
X = np.random.randint(1,11,size=(5,5))

print('Original X = \n', X)


# We sort the columns of X and print the sorted array
print()
print('X with sorted columns :\n', np.sort(X, axis = 0))

# We sort the rows of X and print the sorted array
print()
print('X with sorted rows :\n', np.sort(X, axis = 1))

Original X = 
 [[ 5  6  4  8 10]
 [10  7  1  6  8]
 [ 8  6  3  2  4]
 [ 5  3 10  1  1]
 [ 1 10  7  3  5]]

X with sorted columns :
 [[ 1  3  1  1  1]
 [ 5  6  3  2  4]
 [ 5  6  4  3  5]
 [ 8  7  7  6  8]
 [10 10 10  8 10]]

X with sorted rows :
 [[ 4  5  6  8 10]
 [ 1  6  7  8 10]
 [ 2  3  4  6  8]
 [ 1  1  3  5 10]
 [ 1  3  5  7 10]]


In [ ]:
# Arithmetic operations and Broadcasting
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
# Element-wise addition
sum_array = array_a + array_b
print("Sum of arrays:", sum_array)

# Get square root of each element of array_a
sqrt_array = np.sqrt(array_a)
print("Square root of array_a:", sqrt_array)

# Get exponential of each element of array_b
exp_array = np.exp(array_b)
print("Exponential of array_b:", exp_array)

# Get average of elements in array_a
mean_value = np.mean(array_a, axis=0)
print("Mean of array_a:", mean_value)

#Median, min, max
print("Median", np.median(array_a))
print("Min", np.min(array_a))
print("Max", np.max(array_b))

Sum of arrays: [5 7 9]
Square root of array_a: [1.         1.41421356 1.73205081]
Exponential of array_b: [ 54.59815003 148.4131591  403.42879349]
Mean of array_a: 2.0
Median 2.0
Min 1
Max 6


In [ ]:
#Use Broadcasting to create a 4 x 4 ndarray that has its first column full of `1`s, its second column full of `2`s, its third column full of `3`s, etc..
B = np.arange(1,5)
print(V)

# Resources:
- [Broadcasting](https://numpy.org/devdocs/user/basics.broadcasting.html)
- [Mathematical functions](https://numpy.org/devdocs/reference/routines.math.html#mathematical-functions)
